service: serverless-simple-http-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    APPDYNAMICS_ACCOUNT_NAME: aws-sandbox
    APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: 
    APPDYNAMICS_APPLICATION_NAME: Daves-First-Lambda
    APPDYNAMICS_CONTROLLER_HOST: aws-sandbox.saas.appdynamics.com
    APPDYNAMICS_SERVERLESS_API_ENDPOINT: https://pdx-sls-agent-api.saas.appdynamics.com
    APPDYNAMICS_CONTROLLER_PORT: 443
    APPDYNAMICS_LOG_LEVEL: DEBUG
    APPDYNAMICS_TIER_NAME: NodeLambdaT

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
